// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqojQV2jXrMIvfhCSN50NAmqTW-i6Vhw',
    appId: '1:542582444853:web:15a94dc55ce289b0edf27c',
    messagingSenderId: '542582444853',
    projectId: 'f23aa001-flutter',
    authDomain: 'f23aa001-flutter.firebaseapp.com',
    storageBucket: 'f23aa001-flutter.firebasestorage.app',
    measurementId: 'G-2VFYSH89R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORvTahQoLHmxpW5t9ExwO855wXMfsNNw',
    appId: '1:542582444853:android:b7a33fa1685254e2edf27c',
    messagingSenderId: '542582444853',
    projectId: 'f23aa001-flutter',
    storageBucket: 'f23aa001-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJedpXL-FS1Y7XSUxx-9FxpHlG2_tIlQ',
    appId: '1:542582444853:ios:9f9d6a3441297418edf27c',
    messagingSenderId: '542582444853',
    projectId: 'f23aa001-flutter',
    storageBucket: 'f23aa001-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJedpXL-FS1Y7XSUxx-9FxpHlG2_tIlQ',
    appId: '1:542582444853:ios:9f9d6a3441297418edf27c',
    messagingSenderId: '542582444853',
    projectId: 'f23aa001-flutter',
    storageBucket: 'f23aa001-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFqojQV2jXrMIvfhCSN50NAmqTW-i6Vhw',
    appId: '1:542582444853:web:004cf87acf27d9c4edf27c',
    messagingSenderId: '542582444853',
    projectId: 'f23aa001-flutter',
    authDomain: 'f23aa001-flutter.firebaseapp.com',
    storageBucket: 'f23aa001-flutter.firebasestorage.app',
    measurementId: 'G-H1BZYTH0FG',
  );
}
